config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cooking_sessions, only: %i[index show] do
    resources :reservations, only: %i[create]
  end
  resources :reservations, only: %i[show]

  resource :current_location, only: %i[create]
  namespace :user do
    resource :chef, only: %i[new create show] do
      resource :meal, only: %i[new create]
      resource :cooking_session, only: %i[new create]
    end
  end
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user
  has_many :meals
  has_many :cooking_sessions, through: :meals

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def streams?
    twitch_channel.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :chef
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/user/chefs_controller.rb
class User::ChefsController < ApplicationController
  def new
    @chef = Chef.new
  end

  # post /user/chef
  def create
    @chef = Chef.new(chef_params)
    @chef.user = current_user

    if @chef.save
      redirect_to user_chef_path
    else
      render :new
    end
  end

  def show
    @chef = current_user.chef
  end

  private

  def chef_params
    params.require(:chef).permit(:address)
  end
end

app/controllers/user/cooking_sessions_controller.rb
class User::CookingSessionsController < ApplicationController
  def new
    @cooking_session = CookingSession.new
    @meals = current_user.chef.meals
  end

  def create
    @cooking_session = CookingSession.new(cooking_session_params)
    @cooking_session.address = current_user.chef.address
    @cooking_session.latitude = current_user.chef.latitude
    @cooking_session.longitude = current_user.chef.longitude

    if @cooking_session.save
      redirect_to user_chef_path
      # tentative path that redirects to index of cooking sessions
    else
      render :new
    end
  end

  private

  def cooking_session_params
    params.require(:cooking_session).permit(:max_portions, :end_at, :meal_id, :streaming)
  end

end

app/controllers/user/meals_controller.rb
class User::MealsController < ApplicationController
  def new
    @meal = Meal.new
    @chef = current_user
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.chef = current_user.chef

    if @meal.save
      redirect_to user_chef_path
    else
      render :new
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :description, :photo)
  end
end

app/views/user/chefs/_card.html.erb
<div class="card mb-1 px-5">
  <div class="card-body">
    <div class="d-flex justify-content-between my-3">
     <p class="h4"><strong><%= icon "fa", "user" %> Chef <%= chef.user.username %></strong></p>
      <%= cl_image_tag(
        chef.user.photo.key,
        gravity: "face",
        width: 110,
        height: 110,
        crop: :fill,
        class: "avatar-large bleeding-avatar"
      ) %>
    </div>
    <ul class="list-unstyled mb-3">
      <li><%= icon "fa", "utensils" %> <%= @cooking_session.chef.bio %></li>
      <br>
      <%# Chef experience added manually instead of coding from "(chef model)created_at" %>
      <li><%= icon "fa", "star-of-life" %> Osusowake chef for <%= rand(2..4) %> months</li>
      <% if chef.cooking_sessions.count > 1 %>
        <li><%= icon "fa", "star-of-life" %> <%= chef.cooking_sessions.count %> portions served</li>
      <% end %>
    </ul>
  </div>

  <div>

  </div>
</div>

app/views/user/chefs/_cookbook_card.html.erb
<% if chef.meals.exists? %>
  <h3 class="mb-3">Your Cookbook</h3>
  <div class="row">
    <% chef.meals.each do |meal| %>
      <div class="col-sm-4 col-lg-2">
        <div class="card overflow-hidden mb-3">
          <%= cl_image_tag meal.photo.key, class: "card-img img-fluid", height:194, width:194, crop: :fill %>
          <div class="card-image-info d-flex flex-column p-3">
            <h5 class="card-title flex-grow-1"><%= meal.name %></h5>
            <%= link_to new_user_chef_cooking_session_path, class:"mb-0 text-end small text-decoration-none text-white" do %>
              Schedule cooking <%= icon "fa", "calendar-days" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
      <div class="col-sm-4 col-lg-2 d-flex">
        <%= link_to new_user_chef_meal_path, class:"btn btn-outline-success w-100 mb-3 d-flex align-items-center justify-content-center" do %>
          <%= icon "fa", "circle-plus", class: "me-1" %>
          Add a new dish
        <% end %>
      </div>
<% end %>

app/views/user/chefs/_streaming_card.html.erb
<div class="bg-white rounded overflow-hidden">
  <div style="margin-bottom: -8px" id="twitch-embed<%= cooking_session.id %>"></div>

  <!-- Load the Twitch embed JavaScript file -->
  <script src="https://embed.twitch.tv/embed/v1.js"></script>

  <script type="text/javascript">
    new Twitch.Embed("twitch-embed<%= cooking_session.id %>", {
      width: "100%",
      height: 240,
      layout: "video",
      autoplay: false,
      theme: "light",
      channel: "<%= cooking_session.chef.twitch_channel %>",
      // Only needed if this page is going to be embedded on other websites
      parent: ["embed.example.com", "othersite.example.com"]
    });
  </script>
</div>

app/views/user/chefs/_streaming_panel.html.erb
<div class="bg-white container px-3 py-2 mt-3">
  <h2 class="h6">
    <span class="badge badge-light border border-danger text-danger rounded-1">
      LIVE
    </span>
    NOW BROADCASTING <%= cooking_session.meal.name.upcase %>
  </h2>
  <div id="twitch-embed"></div>

  <!-- Load the Twitch embed JavaScript file -->
  <script src="https://embed.twitch.tv/embed/v1.js"></script>

  <!-- Create a Twitch.Embed object that will render within the "twitch-embed" element -->
  <script type="text/javascript">
    new Twitch.Embed("twitch-embed", {
      width: "100%",
      height: 400,
      channel: "<%= cooking_session.chef.twitch_channel %>",
      // Only needed if this page is going to be embedded on other websites
      parent: ["embed.example.com", "othersite.example.com"]
    });
  </script>
</div>

app/views/user/chefs/new.html.erb
<div class="container">
<h1>Become a Chef</h1>
<h5>Let's Osusowake!</h5>
<h6 class="mb-3">We need your address and a short bio for your profile</h6>
<%# use pundit to prevent non-users from becoming a chef %>
  <%= simple_form_for [@chef], url: user_chef_path do |f| %>
    <%= f.input :address, placeholder: "Enter your address", label: false %>
    <%= f.input :bio, placeholder: "What's the story behind your cooking experience?", label: false %>
    <%= f.submit "Submit", class: "btn btn-secondary mb-3" %>
  <% end %>
</div>

app/views/user/chefs/show.html.erb
<div class="container d-flex justify-content-center my-5">
  <h1 class="mt-3 mb-3">Welcome back <strong><%= @chef.user.username %>!</h1>
</div>
<% if @chef.meals.present? %>
  <div class="container mb-3">
    <h3 class="mb-3">What's Cooking?</h3>
    <div class="grid-lg-2">
      <% @chef.meals.each do |meal| %>
        <% if meal.cooking_sessions.exists? %>
          <% meal.cooking_sessions.upcoming.each do |cooking_session|%>
            <div class="card overflow-hidden">
              <div class="d-flex flex-grow-1">
                <%= cl_image_tag meal.photo.key,  height:92, width:130, crop: :fill, class: "img-fluid object-fit-cover", style: "max-width: 130px" %>
                <div class="p-3">
                  <h5 class="card-title"><%= meal.name %></h5>
                  <h6 class="text-muted"><small>pickup in</small> <%= distance_of_time_in_words_to_now(cooking_session.end_at) %></h6>
                </div>
              </div>
              <div class="progress position-relative rounded-0" style="1rem">
                <div class="progress-bar progress-bar bg-light-green fs-3" role="progressbar"
                style="width: <%= number_to_percentage(cooking_session.ratio_of_portions_reserved * 100, precision: 0) %>;"
                aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                </div>
                <div class="text-end flex-grow-1 position-absolute w-100">
                  <%= cooking_session.portions_reserved %>
                  <span class="small">out of</span>
                  <%= pluralize(cooking_session.max_portions, "portion") %>
                  <span class="small  me-2">
                    reserved
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="container mb-3">
    <%= render "user/chefs/cookbook_card", chef: @chef %>
  </div>
<% else %>
  <div class="container mb-3">
    <h3>Let's make your cookbook!</h3>
    <%= link_to new_user_chef_meal_path, class:"btn btn-outline-success" do %>
      <%= icon "fa", "circle-plus", class: "me-1" %>
      Add a new dish
    <% end %>
  </div>
<% end %>
  <div class="d-flex justify-content-start">
    <%= link_to "Explore meals from other chefs!", cooking_sessions_path, class: "btn btn-outline-secondary mt-1" %></li>
  </div>
</div>