config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cooking_sessions, only: %i[index show] do
    resources :reservations, only: %i[create]
  end
  resources :reservations, only: %i[show]

  resource :current_location, only: %i[create]
  namespace :user do
    resource :chef, only: %i[new create show] do
      resource :meal, only: %i[new create]
      resource :cooking_session, only: %i[new create]
    end
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :chef
  has_many :cooking_sessions
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_one :chef
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/user/chefs_controller.rb
class User::ChefsController < ApplicationController
  def new
    @chef = Chef.new
  end

  # post /user/chef
  def create
    @chef = Chef.new(chef_params)
    @chef.user = current_user

    if @chef.save
      redirect_to user_chef_path
    else
      render :new
    end
  end

  def show
    @chef = current_user.chef
  end

  private

  def chef_params
    params.require(:chef).permit(:address)
  end
end

app/controllers/user/cooking_sessions_controller.rb
class User::CookingSessionsController < ApplicationController
  def new
    @cooking_session = CookingSession.new
    @meals = current_user.chef.meals
  end

  def create
    @cooking_session = CookingSession.new(cooking_session_params)
    @cooking_session.address = current_user.chef.address
    @cooking_session.latitude = current_user.chef.latitude
    @cooking_session.longitude = current_user.chef.longitude

    if @cooking_session.save
      redirect_to user_chef_path
      # tentative path that redirects to index of cooking sessions
    else
      render :new
    end
  end

  private

  def cooking_session_params
    params.require(:cooking_session).permit(:max_portions, :end_at, :meal_id, :streaming)
  end

end

app/controllers/user/meals_controller.rb
class User::MealsController < ApplicationController
  def new
    @meal = Meal.new
    @chef = current_user
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.chef = current_user.chef

    if @meal.save
      redirect_to user_chef_path
    else
      render :new
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :description, :photo)
  end
end

app/views/user/meals/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-sm-10 col-lg-5">
      <h1 class="h2 mb-3 text-center"><strong>What are you cooking?</strong></h1>
      <h5 class="text-muted mb-3 text-center"><strong>Let's add a new dish to your Osusowake list!</strong></h5>
      <%# use pundit to prevent non-chefs from making a meal %>
        <%= simple_form_for [@meal], url: user_chef_meal_path do |f| %>
          <%= f.input :name, placeholder: "Name of your dish", label: false %>
          <%= f.input :description, placeholder: "brief description of your dish", as: :text, label: false %>
          <%= f.input :photo, as: :file, label: false %>
          <div class="d-flex justify-content-end">
            <%= f.submit "Add to your cookbook", class: "btn btn-secondary mb-3"  %>
          </div>
        <% end %>
    </div>
  </div>
</div>