config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cooking_sessions, only: %i[index show] do
    resources :reservations, only: %i[create]
  end
  resources :reservations, only: %i[show]

  resource :current_location, only: %i[create]
  namespace :user do
    resource :chef, only: %i[new create show] do
      resource :meal, only: %i[new create]
      resource :cooking_session, only: %i[new create]
    end
  end
end

app/controllers/current_locations_controller.rb
class CurrentLocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[create]

  def create
    last_location.update_with(query: location_params.values, max_distance: 20)

    redirect_to cooking_sessions_path
  end

  private

  def location_params
    params.require(:location).permit(:latitude, :longitude)
  end
end

app/views/current_locations/_form.html.erb
<div data-controller="current-location">
  <%= simple_form_for :search, url: cooking_sessions_path, method: :get do |f| %>

    <div class="position-relative">
      <%= f.input :query,
        class: "text-end",
        placeholder: "Search from your location",
        label: false
      %>
      <%= button_tag :button, data: { action: "click->current-location#getPosition" }, class: "position-absolute top-0 bottom-0 end-0 bg-transparent px-2 border-0" do %>
        <%= icon "fas", "location" %>
      <% end %>
    </div>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-secondary w-50" title="search">
        Search
      </button>
    </div>
  <% end %>

  <%= form_for(:location, url: current_location_path, data: { current_location_target: "form" }) do |f| %>
    <%= hidden_field :location, :latitude, data: { current_location_target: "latitudeInput" } %>
    <%= hidden_field :location, :longitude, data: { current_location_target: "longitudeInput" } %>
  <% end %>
</div>